- name: installing multiple packages
  hosts: localhost
  tasks: 
  - name: packages
    ansible.builtin.apt:
      name: "{{item.name}}"
      state: "{{item.state}}''
    #list of map
    loop:
    - {name : 'git' , state: 'restarted'}
    - {name: 'postfix' , state: 'absent'}

