- name: installing and run nginx
  hosts: nginx
  become: yes
  tasks: 
    - name: installing nginx
      ansible.builtin.apt:
        name: nginx
        state: installed
      enabled: yes

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
