- name: installing and run nginx
  hosts: nginx
  become: yes #this will give you root access
  tasks: 
  - name: installing nginx
    ansible.builtin.apt:
      name: nginx
      state: present
      

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
