- name: varibles
  hosts: nginx
  become: yes
  vars:
    NAME: siva
    STATE: AP
    DISTRICT: GUNTUR
  
  tasks:
  - name: using varibles
    ansible.builtin.debug:  #for printing we use debug command
      msg: "{{NAME}}IS FROM {{DISTRICT}} AND {{STATE}}"
  - name:  varibales # should not be same
    ansible.builtin.debug:  #for printing we use debug command
      msg: "IN {{STATE}} THERE IS A PLACE CALLED {{DISTRICT}} THERE YOU FIND {{NAME}}"