- name: variables from files
  hosts: localhost #where you install the ansible server
  become: yes
  vars_files: 
  - variableforfile.yaml
  tasks: 
  - name: printing varibles from varibles file
    ansible.builtin.debug:
      msg: "{{NAME}} IS  FROM {{DISTRICT}} IN {{STATE}}"
