- name: vars from inventory
  hosts: localhost
  become: yes
  
  tasks:
  - name: declaring in inventory
    ansible.builtin.debug:
      msg: "user: {{ ansible_user }} , password: {{ ansible_ssh_private_key_file }}"