- name: declaring vars from prompt
  hosts: localhost
  become: yes
  vars_prompt:
  - name: variableuser
    prompt: please enter your name
    private: false
  - name: variablepassword
    prompt: please enter your password
    private: true
  tasks:
  - name: print
    ansible.builtin.debug:
      msg: "username: {{variableuser}} , password: {{variablepassword}}"