- name: passing varibles from args/cli
  hosts: localhost
  become: yes
  tasks:
  - name: printing from cli
    ansible.builtin.debug:
      msg: "Name: {{ name }}, Place: {{ place }}"


#pass like this
#ansible-playbook -i inventory.ini -e "name='siva soma' place='guntur'" vars-cli-args.yaml
